<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
	<PropertyGroup>
		<AssemblyName>ClashChecker</AssemblyName>
		<GenerateAssemblyInfo>False</GenerateAssemblyInfo>
		<TargetFramework>net481</TargetFramework>
		<RuntimeIdentifiers>win-x86</RuntimeIdentifiers>
		<UseWPF>true</UseWPF>
		<Nullable>Enable</Nullable>
		<Platforms>AnyCPU;x86</Platforms>
	</PropertyGroup>
	<PropertyGroup>
		<LangVersion>12.0</LangVersion>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
	</PropertyGroup>
	<PropertyGroup>
	  <PlatformTarget>x86</PlatformTarget>
	  <GenerateDocumentationFile>False</GenerateDocumentationFile>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Dapper" Version="2.1.72" />
		<PackageReference Include="DataGridExtensions" Version="2.9.1" />
		<PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />
	</ItemGroup>
	<ItemGroup>
		<Reference Include="Aveva.Core.Database.Filters">
		  <HintPath>..\References\Aveva.Core.Database.Filters.dll</HintPath>
		</Reference>
		<Reference Include="Aveva.Core.Geometry">
		  <HintPath>..\References\Aveva.Core.Geometry.dll</HintPath>
		</Reference>
		<Reference Include="Microsoft.Data.SqlClient">
		  <HintPath>X:\App\PDMS\PDMS_TEP\TUNINGE3D\DLL-1\Microsoft.Data.SqlClient.dll</HintPath>
		</Reference>
		<Reference Include="Aveva.Core.Database">
			<HintPath>..\References\Aveva.Core.Database.dll</HintPath>
		</Reference>
		<Reference Include="Aveva.Core.Utilities">
			<HintPath>..\References\Aveva.Core.Utilities.dll</HintPath>
		</Reference>
		<Reference Include="Aveva.Core">
			<HintPath>..\References\Aveva.Core.dll</HintPath>
		</Reference>
		<Reference Include="Aveva.Core3D.Clasher">
			<HintPath>..\References\Aveva.Core3D.Clasher.dll</HintPath>
		</Reference>
		<Reference Include="Microsoft.VisualBasic" />
		<Reference Include="PMLNet">
		  <HintPath>..\References\PMLNet.dll</HintPath>
		  <Private>False</Private>
		</Reference>
		<Reference Include="PresentationCore">
		  <HintPath>..\..\..\..\..\..\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8.1\PresentationCore.dll</HintPath>
		</Reference>
		<Reference Include="PresentationFramework">
		  <HintPath>..\..\..\..\..\..\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8.1\PresentationFramework.dll</HintPath>
		</Reference>
		<Reference Include="System.Data" />
		<Reference Include="WindowsBase">
		  <HintPath>..\..\..\..\..\..\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8.1\WindowsBase.dll</HintPath>
		</Reference>
	</ItemGroup>
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
	</Target>
</Project>
