<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
	<PropertyGroup>
		<AssemblyName>ClashChecker</AssemblyName>
		<GenerateAssemblyInfo>False</GenerateAssemblyInfo>
		<TargetFramework>net481</TargetFramework>
		<RuntimeIdentifiers>win-x86</RuntimeIdentifiers>
		<UseWPF>true</UseWPF>
		<Nullable>Enable</Nullable>
		<Platforms>AnyCPU;x86</Platforms>
		<CompanyReferencesPath>\\KPEI-MSK-HQ-AVEVA-FS01\Share\AVEVA\AVEVADLL\CLS</CompanyReferencesPath>
	</PropertyGroup>
	<PropertyGroup>
		<LangVersion>12.0</LangVersion>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
	</PropertyGroup>
	<PropertyGroup>
	  <PlatformTarget>x86</PlatformTarget>
	  <GenerateDocumentationFile>False</GenerateDocumentationFile>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Dapper" Version="2.1.72" />
		<PackageReference Include="DataGridExtensions" Version="2.9.1" />
		<PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />
	</ItemGroup>
	<ItemGroup>
		<Reference Include="Aveva.Core.Database.Filters">
		  <HintPath>$(CompanyReferencesPath)\Aveva.Core.Database.Filters.dll</HintPath>
		</Reference>
		<Reference Include="Aveva.Core.Geometry">
		  <HintPath>$(CompanyReferencesPath)\Aveva.Core.Geometry.dll</HintPath>
		</Reference>
		<Reference Include="Aveva.Core.Database">
			<HintPath>$(CompanyReferencesPath)\Aveva.Core.Database.dll</HintPath>
		</Reference>
		<Reference Include="Aveva.Core.Utilities">
			<HintPath>$(CompanyReferencesPath)\Aveva.Core.Utilities.dll</HintPath>
		</Reference>
		<Reference Include="Aveva.Core">
			<HintPath>$(CompanyReferencesPath)\Aveva.Core.dll</HintPath>
		</Reference>
		<Reference Include="Aveva.Core3D.Clasher">
			<HintPath>$(CompanyReferencesPath)\Aveva.Core3D.Clasher.dll</HintPath>
		</Reference>
		<Reference Include="Microsoft.VisualBasic" />
		<Reference Include="PMLNet">
		  <HintPath>$(CompanyReferencesPath)\PMLNet.dll</HintPath>
		  <Private>False</Private>
		</Reference>
		<Reference Include="PresentationCore" />
		<Reference Include="PresentationFramework" />
		<Reference Include="System.Data" />
		<Reference Include="WindowsBase" />
	</ItemGroup>
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
	</Target>
</Project>
