<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net481</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
	<LangVersion>12</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <PlatformTarget>x86</PlatformTarget>
    <CompanyReferencesPath>\\KPEI-MSK-HQ-AVEVA-FS01\Share\AVEVA\AVEVADLL</CompanyReferencesPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MaterialDesignThemes" Version="5.3.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aveva.ClashChecker.NetCallable\Aveva.ClashChecker.NetCallable.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Aveva.Core">
      <HintPath>\\KPEI-MSK-HQ-AVEVA-FS01\Share\AVEVA\AVEVADLL\CLS\Aveva.Core.dll</HintPath>
    </Reference>
    <Reference Include="Aveva.Core.Database">
      <HintPath>\\KPEI-MSK-HQ-AVEVA-FS01\Share\AVEVA\AVEVADLL\CLS\Aveva.Core.Database.dll</HintPath>
    </Reference>
    <Reference Include="Aveva.Core.Database.Filters">
      <HintPath>\\KPEI-MSK-HQ-AVEVA-FS01\Share\AVEVA\AVEVADLL\CLS\Aveva.Core.Database.Filters.dll</HintPath>
    </Reference>
    <Reference Include="Aveva.Core.Geometry">
      <HintPath>\\KPEI-MSK-HQ-AVEVA-FS01\Share\AVEVA\AVEVADLL\CLS\Aveva.Core.Geometry.dll</HintPath>
    </Reference>
    <Reference Include="Aveva.Core.Utilities">
      <HintPath>\\KPEI-MSK-HQ-AVEVA-FS01\Share\AVEVA\AVEVADLL\CLS\Aveva.Core.Utilities.dll</HintPath>
    </Reference>
    <Reference Include="Aveva.Core3D.Clasher">
      <HintPath>\\KPEI-MSK-HQ-AVEVA-FS01\Share\AVEVA\AVEVADLL\CLS\Aveva.Core3D.Clasher.dll</HintPath>
    </Reference>
    <Reference Include="DataGridExtensions">
      <HintPath>$(CompanyReferencesPath)\DataGridExtensions.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Microsoft.VisualBasic" />
    <Reference Include="PMLNet">
      <HintPath>\\KPEI-MSK-HQ-AVEVA-FS01\Share\AVEVA\AVEVADLL\CLS\PMLNet.dll</HintPath>
    </Reference>
    <Reference Include="PMLNetUtilities">
      <HintPath>\\KPEI-MSK-HQ-AVEVA-FS01\Share\AVEVA\AVEVADLL\CLS\PMLNetUtilities.dll</HintPath>
    </Reference>
    <Reference Include="System.Windows.Forms" />
    <Reference Include="WindowsFormsIntegration" />
  </ItemGroup>


</Project>
