<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ViewForm</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <UseWpf>True</UseWpf>
    <TargetFramework>net481</TargetFramework>
  </PropertyGroup>
	<PropertyGroup>
        <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<BuildProjectReferences>true</BuildProjectReferences>
		<SkipNonexistentProjects>false</SkipNonexistentProjects>
		<LangVersion>12</LangVersion>
	</PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Aveva.ClashChecker.NetCallable\Aveva.ClashChecker.NetCallable.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Aveva.Core.Database">
      <HintPath>D:\AVEVA\Everything3D2.10\Aveva.Core.Database.dll</HintPath>
    </Reference>
    <Reference Include="Aveva.Core.Utilities">
      <HintPath>D:\AVEVA\Everything3D2.10\Aveva.Core.Utilities.dll</HintPath>
	</Reference>
	<Reference Include="PMLNet">
      <HintPath>D:\AVEVA\Everything3D2.10\PMLNet.dll</HintPath>
	</Reference>

</ItemGroup>
</Project>