<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>SQLOBJ</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net481</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup>
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Aveva.Core.Utilities">
      <HintPath>D:\AVEVA\Everything3D2.10\Aveva.Core.Utilities.dll</HintPath>
    </Reference>
    <Reference Include="PMLNet">
      <HintPath>..\References\PMLNet.dll</HintPath>
    </Reference>
    <Reference Include="System.Data" />
  </ItemGroup>
</Project>